package dominio;

public enum Provincia {

	SALTA, ENTRE_RIOS, CATAMARCA, CHUBUT,CHACO, CORDOBA,CORRIENTES, FORMOSA, JUJUY,
	LA_PAMPA, LA_RIOJA, MENDOZA, MISIONES, NEUQUEN, RIO_NEGRO, SAN_JUAN, SAN_LUIS, SANTA_CRUZ,
	SANTA_FE, SANTIAGO_DEL_ESTERO, TIERRA_DEL_FUEGO, TUCUMAN, BUENOS_AIRES, CABA
}
